image: ruby:2.3

before_script:
  - apt-get update -qq && apt-get -y -qq install nodejs
  - gem install bundler --no-ri --no-rdoc
  - bundle check --path vendor/bundle || bundle install --jobs $(nproc) --path vendor/bundle

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master
  cache:
    paths:
      - vendor/bundle

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
  cache:
    paths:
      - vendor/bundle
